### ISSUE TITLE
一部のローマ字が誤って変換される

### ISSUE THREAD

**Issue by Meatwo310** [Meatwo310/tsuki-chat#19]
そうはならんやろ

**Comment by sysnote8main** [comment]
辞書データがおそらく誤っているものと思われます。
https://github.com/Meatwo310/tsuki-chat/blob/a55be791c70bd3408f8c93c2ae31feb434ce63aa/src/main/resources/assets/japaneseromajiconverter/romaji_to_hiragana.txt#L122-L126

**Comment by Meatwo310** [comment]
重複して登録されてますわね
https://github.com/Meatwo310/tsuki-chat/blob/a55be791c70bd3408f8c93c2ae31feb434ce63aa/src/main/resources/assets/japaneseromajiconverter/romaji_to_hiragana.txt#L29C1-L33C5

**Comment by sysnote8main** [comment]
ということは、消せば治りそう？

**Comment by Meatwo310** [comment]
おそらくは

**Comment by Meatwo310** [comment]
重複してるのはこの辺
```
la
le
li
lo
lu
lya
lye
lyi
lyo
lyu
```

**Comment by Meatwo310** [comment]
あちゃあ
https://github.com/Meatwo310/tsuki-chat/blob/a55be791c70bd3408f8c93c2ae31feb434ce63aa/src/main/resources/assets/japaneseromajiconverter/romaji_to_hiragana.txt#L139-L143
https://github.com/Meatwo310/tsuki-chat/blob/a55be791c70bd3408f8c93c2ae31feb434ce63aa/src/main/resources/assets/japaneseromajiconverter/romaji_to_hiragana.txt#L242-L246

**Comment by Meatwo310** [comment]
#21 #22
