### ISSUE TITLE
ユーザー辞書を実装する

### ISSUE THREAD

**Issue by Meatwo310** [Meatwo310/tsuki-chat#24]

**Comment by medakoro** [comment]
"hairan"ってやると下ネタですので早めにお願いします()
こんな感じでユーザー辞書をお願いします

`{
  "kinsi":
          {
            "word":"hairan"
            "replace":"はいらん"
          }
}`

**Comment by Meatwo310** [comment]
Forge Config API上の制約だと`String[]`になりそう
なのでこんな感じ？
```
[
  "排卵,はいらん",
  ...
]
```

**Comment by Meatwo310** [comment]
別にコンフィグで設定させなくてもいいのか
コマンドで個人個人が設定できたほうが使いやすそうだなこれ

**Comment by Meatwo310** [comment]
となると別に`String[]`じゃなくていい
`Map<String, String>`でいいかな？

**Comment by medakoro** [comment]
ん-...
そこらへんわからないからめーとぅーさんが分かりやすい&簡単な方でいいよ(

**Comment by medakoro** [comment]
あとhttps://github.com/Meatwo310/tsuki-chat/issues/25 これユーザー辞書追加したら治るんじゃないかな

**Comment by Meatwo310** [comment]
ユーザー辞書とグローバル辞書を追加する

**Comment by Meatwo310** [comment]
done
